# Конфигурация проекта Serena для 1C:Enterprise
# Этот файл настраивает поведение Serena для работы с проектом 1С

project_name: "example-1c-project"
language: "bsl"  # BSL - язык 1С:Предприятие

# Игнорируемые пути - стандартные служебные каталоги 1С
ignored_paths:
  - "out/"              # Каталог выгрузки конфигурации
  - "DT-INF/"          # Служебная информация EDT
  - ".metadata/"       # Метаданные конфигурации
  - "bin/"             # Бинарные файлы
  - "ConfigDumpInfo/"  # Информация о выгрузке
  - "Reports/"         # Отчеты (если не нужно анализировать)
  - "DataProcessors/"  # Обработки (если не нужно анализировать)
  - "*.cf"             # Файлы конфигурации
  - "*.dt"             # Файлы выгрузки
  - "*.epf"            # Внешние обработки
  - "*.erf"            # Внешние отчеты
  - "*.cfe"            # Файлы расширений

# Исключенные инструменты (если какие-то не нужны для 1С)
excluded_tools: []

# Дополнительные инструменты (включаем BSL-специфичные)
included_optional_tools:
  - get_current_config      # Диагностика конфигурации
  - initial_instructions    # Инструкции для проекта
  - restart_language_server # Перезапуск BSL Language Server
  - summarize_changes       # Сводка изменений
  - switch_modes           # Переключение режимов работы
  - delete_lines           # Удаление строк
  - insert_at_line         # Вставка в строку
  - replace_lines          # Замена строк

# Проект доступен для редактирования
read_only: false

# Учитывать .gitignore файлы
ignore_all_files_in_gitignore: true

# Начальный промпт для работы с проектом 1С
initial_prompt: |
  Этот проект содержит исходный код конфигурации 1С:Предприятие.

  Ключевые особенности проекта:
  - Язык разработки: BSL (1C:Enterprise script)
  - Используется платформа 1С:Предприятие 8.3.26
  - Применяются стандарты разработки из "Единого руководства по правилам разработки 1С"

  При работе с кодом учитывай:
  - Стандарты именования объектов и переменных 1С
  - Правила работы с БСП (Библиотека стандартных подсистем)
  - Требования к комментированию кода
  - Принципы архитектуры 1С-решений

  Приоритет источников информации:
  1. Приоритетные подходы реализации (эталонные шаблоны)
  2. Сценарии разработки проекта
  3. Документация платформы 1С:Предприятие 8.3.26
  4. Правила работы с Git
  5. Интернет-источники

# Кодировка файлов (UTF-8 для современных проектов 1С)
encoding: "utf-8"