# Конфигурация проекта Serena для демо-проекта учета
project_name: "demo-accounting"
language: "bsl"

# Игнорируемые пути - стандартные для 1С проектов
ignored_paths:
  # Выходные каталоги
  - "out/"
  - "build/"
  - "dist/"

  # Служебные каталоги 1С
  - "DT-INF/"
  - ".metadata/"
  - "ConfigDumpInfo/"
  - "bin/"

  # Файлы конфигурации (бинарные)
  - "*.cf"
  - "*.dt"
  - "*.epf"
  - "*.erf"
  - "*.cfe"

  # Временные файлы
  - "*.tmp"
  - "*.bak"
  - "*~"

  # Логи и отладочная информация
  - "*.log"
  - "debug/"
  - "logs/"

# Исключенные инструменты (при необходимости)
excluded_tools: []

# Дополнительные инструменты для BSL разработки
included_optional_tools: []

# Проект доступен для редактирования
read_only: false

# Учитывать .gitignore файлы
ignore_all_files_in_gitignore: true

# Начальный промпт для контекста проекта
initial_prompt: |
  Демонстрационный проект учетной системы на платформе 1С:Предприятие 8.3.26
  
  Особенности проекта:
  - Базовая конфигурация для ведения учета товаров и услуг
  - Использует стандартные объекты метаданных 1С
  - Применяет принципы разработки согласно стандартам 1С
  
  Соблюдайте принципы разработки:
  - Стандарты кодирования 1С
  - Правила именования объектов
  - Комментирование кода на русском языке
  - Использование типовых решений

  Приоритет документации:
  1. Приоритетные подходы реализации
  2. Сценарии разработки проекта
  3. Документация платформы 1С:Предприятие
  4. Внешние источники

# Кодировка файлов
encoding: "utf-8"